### ISSUE TITLE
Request for documentation: negative arc index is -1 based

### ISSUE THREAD

**Issue by tomvantilburg** [topojson/topojson-specification#10]
Took me a while to find out that you cannot just use Math.abs(idx) to get the correct reference to an arc when the index is negative (and the coordinate order needs to be reversed). Although I got it after reading the docs 3 times (2.1.4. Arc Indexes), it would be helpful to write this down more explicit.

Ultimately I think a 1-based index might be more appropriate for the arcs, although it might introduce other inconsistencies. A solution might be to always put an empty value at the first position, so iterators still do their jobs.

**Comment by mbostock** [comment]
The recommended approach in JavaScript (and other languages with similar bitwise operators) is to use [bitwise NOT](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#Bitwise_NOT): `~i`. I’ve added this recommendation to the specification.

**Comment by tomvantilburg** [comment]
Thanks. Clarifies a lot!
