### ISSUE TITLE
What's the proper mime type for serving a topojson file?

### ISSUE THREAD

**Issue by benbalter** [topojson/topojson-specification#11]
Should it be `application/json` or `application/geo+json` (or something else)?

**Comment by scardine** [comment]
The file format is valid JSON, so `application/json` is not incorrect. I would use that unless your application needs to differentiate between other JSON-based data formats at the request level.

**Comment by mbostock** [comment]
I recommend `application/json` until there is a more specific alternative that is standardized (such as `application/topo+json`, but I’m not familiar with the standardization process).

**Comment by jseppi** [comment]
Sean Gillies over at Mapbox spearheaded the `application/geo+json` effort (ref: [RFC7946](https://tools.ietf.org/html/rfc7946)), so if you are interested in heading down that road you might want to talk to him. As a casual observer, it seemed like quite an arduous process.

**Comment by benbalter** [comment]
:metal:. We're going with `application/json` for GitHub Pages, but wanted to check in to be sure (because since the RFC, `geojson` is now `application/geo+json`). Thanks for the context.
